### ISSUE TITLE
doesn't compile on versions >= 1.33 && < 1.39

### ISSUE THREAD

**Issue by m4rch3n1ng** [vorner/arc-swap#197]
i assume this is unintentional, as you are specifically pulling in `rustversion` to support older versions of rust, but #185 accidentally introduced rust 1.39 features (`pin_into_inner`), while only gating the impl behind rust 1.33:

```
$ cargo +1.36 check -q
error[E0658]: use of unstable library feature 'pin_into_inner'
   --> src/ref_cnt.rs:186:32
    |
186 |         Arc::into_raw(unsafe { Pin::into_inner_unchecked(me) }) as *mut T
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/60245

error[E0658]: use of unstable library feature 'pin_into_inner'
   --> src/ref_cnt.rs:207:41
    |
207 |         let me = Arc::into_raw(unsafe { Pin::into_inner_unchecked(ptr::read(me)) });
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/60245

error[E0658]: use of unstable library feature 'pin_into_inner'
   --> src/ref_cnt.rs:229:31
    |
229 |         Rc::into_raw(unsafe { Pin::into_inner_unchecked(me) }) as *mut T
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/60245

error[E0658]: use of unstable library feature 'pin_into_inner'
   --> src/ref_cnt.rs:250:40
    |
250 |         let me = Rc::into_raw(unsafe { Pin::into_inner_unchecked(ptr::read(me)) });
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/60245

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.

To learn more, run the command again with --verbose.
```

1.31 and 1.32 work however, as that impl is only active for rust > 1.33

i personally don't care about versions that old, but i noticed this while checking why `arc-swap` needs `rustversion` and thought i should inform you.

**Comment by vorner** [comment]
Thank you, it's indeed unintentional, I've published a fix.
